version: '3.8'

services:
  # MongoDB for User Service
  mongodb_user:
    image: mongo:latest
    container_name: mongodb_user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user_service_db
    volumes:
      - user_data:/data/db

  # User Service
  user_service:
    build: ./user-service
    container_name: user_service
    ports:
      - "5000:5000"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongodb_user

  # MongoDB for Product Service
  mongodb_product:
    image: mongo:latest
    container_name: mongodb_product
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: product_service_db
    volumes:
      - product_data:/data/db

  # Product Service
  product_service:
    build: ./product-service
    container_name: product_service
    ports:
      - "5001:5001"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongodb_product

  # MongoDB for Order Service
  mongodb_order:
    image: mongo:latest
    container_name: mongodb_order
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: order_service_db
    volumes:
      - order_data:/data/db

  # Order Service
  order_service:
    build: ./order-service
    container_name: order_service
    ports:
      - "5002:5002"
    env_file:
      - ./order-service/.env
    depends_on:
      - mongodb_order

volumes:
  user_data:
  product_data:
  order_data:
